### ISSUE TITLE
find_package(OpenCV REQUIRED)

### ISSUE THREAD

**Issue by eduherminio** [glemaitre/traffic-sign-detection#11]
Can anyone with OpenCV 2.x confirm that
`find_package(OpenCV REQUIRED core highgui imgproc features2d calib3d) `
instead of
`find_package(OpenCV 2.4.8 REQUIRED core highgui imgproc features2d calib3d)`
works for them, in /src/cmake/findDependencies.cmake?

**Comment by glemaitre** [comment]
It should work
