### ISSUE TITLE
make error for undefined references

### ISSUE THREAD

**Issue by kuonangzhe** [glemaitre/traffic-sign-detection#13]
Nice work! But one point is that I followed the installation for traffic-sign-detection and got a make error in the final step as follows.

Do you have any suggestions for what might be the reason of the error?  Thank you so much!

chongzhaomao@ChongzhaoMao:~/Downloads/traffic-sign-detection-master/build$ make 
[  7%] Built target common
[ 22%] Built target img_processing
[ 29%] Built target optimization
Linking CXX executable /home/chongzhaomao/Downloads/traffic-sign-detection-master/bin/main
CMakeFiles/main.dir/main.cpp.o: In function `main':
main.cpp:(.text+0x116): undefined reference to `cv::imread(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
main.cpp:(.text+0x215): undefined reference to `cv::Exception::Exception(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
main.cpp:(.text+0x517): undefined reference to `cv::imwrite(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
main.cpp:(.text+0x1384): undefined reference to `cv::namedWindow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
main.cpp:(.text+0x13fe): undefined reference to `cv::imshow(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, cv::_InputArray const&)'
../img_processing/libimg_processing.a(segmentation.cpp.o): In function `segmentation::seg_norm_hue(cv::Mat const&, cv::Mat&, int const&, int, int, int)':
segmentation.cpp:(.text+0x3fe): undefined reference to `cv::Exception::Exception(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
../img_processing/libimg_processing.a(colorConversion.cpp.o): In function `colorconversion::convert_rgb_to_ihls(cv::Mat const&, cv::Mat&)':
colorConversion.cpp:(.text+0x64e): undefined reference to `cv::Exception::Exception(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)'
collect2: error: ld returned 1 exit status
apps/CMakeFiles/main.dir/build.make:98: recipe for target '/home/chongzhaomao/Downloads/traffic-sign-detection-master/bin/main' failed
make[2]: *** [/home/chongzhaomao/Downloads/traffic-sign-detection-master/bin/main] Error 1
CMakeFiles/Makefile2:227: recipe for target 'apps/CMakeFiles/main.dir/all' failed
make[1]: *** [apps/CMakeFiles/main.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by glemaitre** [comment]
gcc does not find opencv apparently or at least the `imread` function. You need to check if you have opencv properly installed and that they it is still in the namespace cv

**Comment by kuonangzhe** [comment]
Thanks for the help!
