### ISSUE TITLE
 log chromatic format 

### ISSUE THREAD

**Issue by cvmaker93** [glemaitre/traffic-sign-detection#8]
// Function to convert an RGB image (uchar) to log chromatic format (double)
void rgb_to_log_rb(const cv::Mat& rgbImage, std::vector< cv::Mat >& log_chromatic_image) {}

Could you tell me what the purpose of this funciton?And what is the  log chromatic format ? I can not find any information about this .Thank you!

**Comment by glemaitre** [comment]
It is a color conversion. Check this [publication](https://hal-univ-bourgogne.archives-ouvertes.fr/hal-00627903/document/) to have more information
